networks:
  shared:
    name: shared
    driver: bridge
  auth-gateway:
    name: auth-gateway
    driver: bridge

include:
  - auth/docker-compose.yml
  - gateway/docker-compose.yml
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - shared

volumes:
  rabbitmq_data:
