networks:
  shared:
    name: shared
    driver: bridge
  auth-gateway:
    name: auth-gateway
    driver: bridge
  transaction-gateway:
    name: transaction-gateway
    driver: bridge
  messaging:
    name: messaging
    driver: bridge
  auth-cache:
    name: auth-cache
    driver: bridge

include:
  - auth/docker-compose.yml
  - gateway/docker-compose.yml
  - transaction/docker-compose.yml
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - messaging

volumes:
  rabbitmq_data:
